---
# yamllint disable rule:line-length
name: "Build Test Image"

"on":
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  IMAGE_URL: ghcr.io/${{ github.repository }}:test
  PLATFORMS: "linux/amd64,linux/arm64"

jobs:
  build-push:
    name: Build-Push
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write

    steps:
      - name: start
        run: echo "Start with ${PLATFORMS}, ${IMAGE_URL}"

      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORMS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Test
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: ${{ env.PLATFORMS }}
          push: true
          pull: true
          tags: ${{ env.IMAGE_URL }}

      - name: Test Script
        run: |
          docker run --rm "$IMAGE_URL" "/test.sh"

      - name: Test Trivy
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: ${{ env.IMAGE_URL }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'MEDIUM,CRITICAL,HIGH'
